### ISSUE TITLE
ImportError: cannot import name 'dedent' from 'matplotlib.cbook'

### ISSUE THREAD

**Issue by jmartens** [matplotlib/legacycontour#1]
Import of legacycontour fails on

```ImportError: cannot import name 'dedent' from 'matplotlib.cbook'```

According to [this post](https://github.com/matplotlib/basemap/issues/494#issuecomment-723791305) it can be replaced by 

`from inspect import cleandoc as dedent`

**Comment by WeatherGod** [comment]
closed via #2
